### ISSUE TITLE
Text markup

### ISSUE THREAD

**Issue by doc97** [doc97/TxtAdv#10]
## Tasks
- [x] #6 Abstract text markup parsing
- [x] #14 Convert std::string text to Text objects
- [x] #11 Text style
- [x] #12 Text color
- [x] #21 Escape character '\\' support
- [x] #22 Text size
- [x] #23 Text tags
- [x] #24 Text color types
